repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
      # - id: no-commit-to-branch
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: local
    hooks:
      # - id: ruff
      #   name: ruff
      #   entry: ruff
      #   language: system
      #   types: [python]
      #   args:
      #     - "."
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args:
          - "."
      - id: pyright
        name: pyright
        language: system
        entry: pyright
        types: [python]
      # - id: pytest
      #   name: pytest
      #   types: [python]
      #   entry: pytest
      #   language: system
      #   pass_filenames: false
      #   always_run: true
