# create a file named .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      # - id: pylint
      #   name: pylint
      #   stages: [commit]
      #   language: system
      #   entry: pylint --disable=C0116 --ignore=venv
      #   types: [python]

      # - id: flake8
      #   name: flake8
      #   stages: [commit]
      #   language: system
      #   entry: flake8
      #   types: [python]

      # - id: bandit
      #   name: bandit
      #   stages: [commit]
      #   language: system
      #   entry: bandit
      #   types: [python]

      # - id: mypy
      #   name: mypy
      #   stages: [commit]
      #   language: system
      #   entry: mypy
      #   types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort --profile=black --virtual-env=venv
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]
